- name: Instalando o Docker
  shell: curl -fsSL https://get.docker.com | bash
<<<<<<< HEAD
  notify: Restart Docker
=======
>>>>>>> 6fc690f72ef91fe5d1181c469f008894f92a492f

- name: Adicionando as chaves do repo apt do k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adicionando o repo do k8s
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Instalando os pacotes kubeadm, kubelet e kubectl
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
<<<<<<< HEAD
  notify: Restart Kubelet
=======
>>>>>>> 6fc690f72ef91fe5d1181c469f008894f92a492f
